### PR TITLE
Introduce new Type classes.

### PR DESCRIPTION
**Pull request by ienkovich**
This is my initial proposal for new Type classes for HDK public API which should replace the existing `SQLTypeInfo` class. It is supposed to cover all currently used types except `kCOLUMN` and `kCOLUMN_LIST` whose purpose I don't fully uderstand right now.

This introduces `hdk::ir::Context` class which assumes that all IR structures are created within some context. Working within a single context is not thread-safe. I suppose we will have some kind of QueryContext later which would use `hdk::ir::Context` as a base class or a member.

All new structures are immutable which allows easy re-use and decreases the number of `Type` objects created within a single `hdk::ir::Context`. Context owns all `Type` objects and plain pointers are used everywhere. This is similar to what LLVM has.

Since all objects are immutable, we don't have any `set*` methods in API, so I tried to use concise naming and avoided `get` prefixes for all methods. Velox uses a similar notation and I found it nice. BTW, I'm going to make `Expr` classes immutable too (right now there are rare cases where we make modifications).

Previously, we referenced Google Coding Style as the one we try to follow, but in fact, there is no code in OmniSci/HDK that completely follows it. I tried to follow Google Coding Style with the difference, that I use lowerCamelCase naming for methods instead of CamelCase which matches a lot of existing code.

The original type system and arrow have multiple interval types. IIUC Arrow's `DayTimeIntervalType` refers to some kind of structure whose fields hold days and milliseconds and that makes it a special type. For OmniSci types, it seems there is not much difference between different datetime and interval types except the used time unit.  I didn't get why we cannot use a single interval class so far, so decided to start with a single class and add more if we really need it.

I included implementation files but would like to start the discussion with headers first.

### CODE REVIEW

**Review by kurapov-peter — COMMENTED** [review]
A couple of things that first came to mind (this only touches IR/Type.h):
1. Why are we using the Hungarian notation for enums ids and only for them? I find this unnecessary and inconsistent with the style (well, the ideal version of it). Is there any specific use to it?
2. What is the motivation for moving the declaration of `TimeUnit` out of the `DateTimeBaseType`? I.e. the `Precision` lives inside of a floating point type.
3. Can we forbid any potential implicit casting and make all the types' constructors explicit?
4. What does the "Ext" prefix signify in the `ExtDictionaryType`?
5. What is supposed to happen if I create an integer of size 7? :) Or more general, why don't we separate types for doubles and floats, and such?

**Comment by ienkovich** [comment]
> A couple of things that first came to mind (this only touches IR/Type.h):
> 
> 1. Why are we using the Hungarian notation for enums ids and only for them? I find this unnecessary and inconsistent with the style (well, the ideal version of it). Is there any specific use to it?

That just follows the Google style guide. There is no consistency in the current OmniSci code style. We have to choose something to be used for our public API at least.

> 2. What is the motivation for moving the declaration of `TimeUnit` out of the `DateTimeBaseType`? I.e. the `Precision` lives inside of a floating point type.

`FloatingPointType::kDouble` looks OK to me, `DateTimeBaseType::kDay` doesn't. It's more of a technical class than a part of the type system. 

> 3. Can we forbid any potential implicit casting and make all the types' constructors explicit?

There are no public constructors, all of them except `NullType` get more than one arg, Type objects are always used by a pointer. No room for implicit casts I guess :) 

> 4. What does the "Ext" prefix signify in the `ExtDictionaryType`?

It stands for 'External'. Meaning that type references the external dictionary which stored the actual data. In Arrow, dictionary type means the dictionary itself is a part of data. 

> 5. What is supposed to happen if I create an integer of size 7? :) Or more general, why don't we separate types for doubles and floats, and such?

You would get the `UnsupportedTypeError` exception. I believe, that having size encoded in type id might require bigger `case` handlers in multiple places and would make it harder to add support for some new type (like int128). We have different size options for integer, float, date, time, interval, and external dictionary. Having all those `kDataeSmall`, `kDate`, `kDateBig` for every type looks too much. And having it for integers only - inconsistent.

But that's just my view. Arrow has IDs for possible sizes of integers, floats, dates, and time. LLVM uses a generic Integer type.

**Comment by alexbaden** [comment]
`kCOLUMN` and `kCOLUMN_LIST` are table function input types -- basically column and set of columns.

**Comment by alexbaden** [comment]
> Previously, we referenced Google Coding Style as the one we try to follow, but in fact, there is no code in OmniSci/HDK that completely follows it. I tried to follow Google Coding Style with the difference, that I use lowerCamelCase naming for methods instead of CamelCase which matches a lot of existing code.
> 

The goal is to follow the Google style guide with some small exceptions. I don't remember all of them, but RelAlgExecutor is usually closest to correct. lowerCamelCase is the big one -- personally I don't like capitalizing class member names as it makes it easier to confuse them with the class name. 


> The original type system and arrow have multiple interval types. IIUC Arrow's `DayTimeIntervalType` refers to some kind of structure whose fields hold days and milliseconds and that makes it a special type. For OmniSci types, it seems there is not much difference between different datetime and interval types except the used time unit. I didn't get why we cannot use a single interval class so far, so decided to start with a single class and add more if we really need it.
> 

Don't have a good answer here -- "high precision" (nanoseconds, microseconds, perhaps milliseconds) time used a different runtime at one point than "regular" time, and that went through a few revisions. Could be leftover from that work.

**Comment by ienkovich** [comment]
I added Column and ColumnList types. Also added conversion between `Type` and `SQLTypeInfo` which will be required for a gradual type system replacement.

**Comment by ienkovich** [comment]
Fixed some bugs revealed during my experiments on replacing `SQLTypeInfo` with `hdk::ir::Type` and added `withNullable` method.

**Comment by ienkovich** [comment]
Added default context which will be very useful during transition period.

**Pull request closed without merging**
