### PR TITLE
Move to LLVM 12.

### PR DESCRIPTION
**Pull request by ienkovich**

### CODE REVIEW

**Comment by alexbaden** [comment]
Will this break our ci on jit-engine branch if we merge it now?

**Comment by ienkovich** [comment]
> Will this break our ci on jit-engine branch if we merge it now?

It worked for the initial version but somehow broke after the latest rebase. Will look into it, it's supposed to switch CI to LLVM 12 and pass.

**Comment by ienkovich** [comment]
@leshikus Can you help me to understand what is going on here with tests failure? It has compilation errors while build tasks pass and it's not supposed to be different in conda env comparing to build tasks.

**Comment by leshikus** [comment]
@ienkovich  looking into it

**Comment by leshikus** [comment]
I believe there may be a problem with conda cache; there is an option in .github/workflows/build.xml to regenerate the cache; it likely have to be turned on to regenerate the cache when major dependency change happens; testing this

**Comment by leshikus** [comment]
The previous guess is incorrect; something does not work as expected in "download artifact functionality"

**Comment by ienkovich** [comment]
> The previous guess is incorrect; something does not work as expected in "download artifact" functionality

What's the impact? Does it happen only when PRT has a significant change in conda env? Can it work eventually if we simply restart CI for the PR?

**Comment by leshikus** [comment]
@ienkovich I have prepared the fix, https://github.com/intel-ai/omniscidb/pull/423

**Comment by leshikus** [comment]
There was a bug in my scripts, a newer cache version created during a build step was unavailable during a test step. Need to use two different download-artifact routines for an old cache and a newer cache.

**Comment by ienkovich** [comment]
> @ienkovich I have prepared the fix, #423

Thanks! Let's see if it helps.

**Comment by alexbaden** [comment]
With `alex/llvm13`, this works nicely on my llvm 13 system now.

**Pull request merged**
