### PR TITLE
Remove Arrow DC dependency

### PR DESCRIPTION
**Pull request by kurapov-peter**
I was building a docker container with dependencies and the double conversion library is missing after installing arrow. I tried a bunch of things (mainly installing more related libs) but none of them worked. So I tried removing the lib altogether. It seems like it doesn't break anything. Any idea what is this lib used for?

### CODE REVIEW

**Comment by alexbaden** [comment]
Looks like Arrow vendors it -- https://github.com/apache/arrow/tree/master/cpp/src/arrow/vendored/double-conversion. I can see where it is a build dependency for Arrow and Folly but do not understand why it is a build dependency for this repo.

Did `libdouble-conversion-dev` not fix the issue in the container?

**Comment by kurapov-peter** [comment]
> Did `libdouble-conversion-dev` not fix the issue in the container?

It builds with the lib installed separately, but I was unsure if it would cause problems since arrow vendors it. I assumed the package should have installed appropriate libs along with `libarrow-dev`.

Removing the dep does not introduce any new failures to our tests. So it either already has all the required symbols or we don't use them at all. Any reason to add the lib to dependencies?

**Comment by alexbaden** [comment]
It's probably fine, but it gives me some pause since our test coverage is pretty limited here, and we could have some sort of import issue caused by a runtime dependency failure -- though I don't know enough to say how likely that is. Plus we're only removing in one container in this PR, vs all our different packages like our conda envs (which would then propagate through CI and give a little more confidence).

**Comment by kurapov-peter** [comment]
Ok, let's leave it as is. I'll add dc as a dependency for our containers.

**Pull request closed without merging**
