### PR TITLE
(first step) added dockers to CI

### PR DESCRIPTION
**Pull request by leshikus**
the first step: no cache and tests

### CODE REVIEW

**Comment by leshikus** [comment]
added caching

**Comment by alexbaden** [comment]
Does this save the Docker build artifacts (namely the images) somewhere, or just build to ensure the build works?

**Comment by leshikus** [comment]
@alexbaden 1) the build caches image layers to speed up image creation; 2) there is a possibility to push the images to docker.io changing some “push” var to true; 3) or instead I can implement something using github artifacts, this is not implemented and due to layered nature of docker images I’m not aware of a straightforward way to do this; 4) for CUDA the tests: they are run on our server, so one can just attach to that container to debug

**Review by alexbaden — APPROVED** [review]

**Comment by kurapov-peter** [comment]
Hi, could you please document how do I build, say, a development docker image for L0 development now?

**Pull request merged**
