### PR TITLE
Switch from SQLTypeInfo to hdk::ir::Type (part 4)

### PR DESCRIPTION
**Pull request by ienkovich**
This part switches `ArrowStorage` API to `hdk::ir::Type` for table creation.

### CODE REVIEW

**Comment by alexbaden** [comment]
I just got the same one after my merge. Bad merge order?

**Comment by ienkovich** [comment]
Regression might have been introduced by #493 which misses this CI check.

**Comment by leshikus** [comment]
@ienkovich tests are run on my server, you can start and then attach to `omni-build` container

**Comment by alexbaden** [comment]
@ienkovich does this fix the other failing test on `jit-engine` branch currently?

**Comment by ienkovich** [comment]
> @ienkovich does this fix the other failing test on `jit-engine` branch currently?

No. The current failure on `jit-engine` branch is flaky. It might appear on any of the 3 runs of `ArrowBasedExecuteTest`. Currently, I don't know which exact patch has introduced it. I will work on this problem next week.

**Review by alexbaden — APPROVED** [review]

**Pull request merged**
