### PR TITLE
Pull some commits from upstream

### PR DESCRIPTION
**Pull request by alexbaden**

### CODE REVIEW

**Comment by alexbaden** [comment]
Tests currently failing:
```
The following tests FAILED:
	  9 - ArrowBasedExecuteTest (Failed)
	 10 - ArrowBasedExecuteTestColumnarOutput (Failed)
	 29 - ArrayTest (Failed)
	 68 - UdfTest (Failed)
```

**Comment by alexbaden** [comment]
`UdfTest` and `ArrayTest` failures are LLVM 13 specific and not related to this patch.
The `TimestampPrecisionFormat` tests in `ArrowBasedExecuteTest` were failing with Arrow 7:
```
[ RUN      ] Select.TimestampPrecisionFormat
unknown file: Failure
C++ exception with description "Invalid: In CSV column #1: CSV conversion error to timestamp[us]: expected no zone offset in '2012-05-22 01:02:03.000003Z'" thrown in the test body.
[  FAILED  ] Select.TimestampPrecisionFormat (1 ms)
[----------] 1 test from Select (1 ms total)
```
On the deps version of Arrow (4 or 5?) this test passes. But removing the timezone from the test resolved the issue. @ienkovich is this expected? I've made that change in a separate commit in case the issue is somewhere else.
I've ported the `ExecuteTest` changes to `ArrowBasedExecuteTest` and on standard deps `sanity_tests` now passes.

**Comment by ienkovich** [comment]
> On the deps version of Arrow (4 or 5?) this test passes. But removing the timezone from the test resolved the issue. @ienkovich is this expected? I've made that change in a separate commit in case the issue is somewhere else.

I'm not aware of all changes they made in Arrow parsers, but I guess we should just follow their changes and switch to the new Arrow with your patch. I saw they added more conversions in new versions that would allow us to enable JSON parsing for arrays of decimals and some others.

**Review by ienkovich — APPROVED** [review]
I got clean testing on this branch with useful patches

**Pull request merged**
