### PR TITLE
Remove OmniSci components we don't need for HDK

### PR DESCRIPTION
**Pull request by ienkovich**
This branch is the current state of my work on unrequired components removal. PR might be too big for a single review, so I have smaller PRs with patches from this branch: #348 #350 
But we can also merge this one to speed it up

### CODE REVIEW

**Comment by alexbaden** [comment]
I pushed a rebased version of my branch in #353  called `alex/sync_rebase`, on top of this branch. https://github.com/intel-ai/omniscidb/tree/alex/sync_rebase

I have not ported the changes from `ExecuteTest` over, but everything else seems to at least build. 

If that branch looks good, then I think we can easily land this one and port the remaining changes from ExecuteTest over. That is one unfortunate part of deleting `ExecuteTest` -- it is harder to keep things in sync going forward.

**Comment by kurapov-peter** [comment]
I assume this means we're moving to arrow based tests only. Could you please clarify what changes are required to run standalone queries such as for example: https://github.com/intel-ai/omniscidb/blob/pakurapo/multifrag-heterogeneous/Benchmarks/taxi/taxi_bench.cpp ?

**Comment by kurapov-peter** [comment]
ArrowBasedExecuteTest hangs with ENABLE_CUDA=on for me. Can we fix it prior to removing the original ExecuteTest flow?

**Comment by ienkovich** [comment]
> ArrowBasedExecuteTest hangs with ENABLE_CUDA=on for me. Can we fix it prior to removing the original ExecuteTest flow?

We can wait, but it looks like you are the only one with a system to debug the problem. Are going to work on this by yourself or provide me with access and instruction on how to reproduce the problem?

**Comment by kurapov-peter** [comment]
The hanging issue is llvm-11 specific. I couldn't reproduce it with llvm-9.

**Comment by ienkovich** [comment]
@alexbaden If the problem was not due to my changes, then probably merge this one?

**Comment by ienkovich** [comment]
The recent commit broke the build for this branch. Need to fix...

**Comment by kurapov-peter** [comment]
Oh, sorry about that

**Comment by kurapov-peter** [comment]
Errr, I take that back, it just hang on llvm 9.

**Comment by ienkovich** [comment]
I've resolved build issues. Tests also pass now (at least on CPU)

**Comment by kurapov-peter** [comment]
Fixed hanging in #355

**Comment by ienkovich** [comment]
@alexbaden Can proceed with this one then

**Review by alexbaden — APPROVED** [review]

**Review by kurapov-peter — APPROVED** [review]
LGTM

**Pull request merged**
